### ISSUE TITLE
Use Ipython shells to run examples in docs

### ISSUE THREAD

**Issue by ibell** [ljvmiranda921/pyswarms#107]
Are you interested in converting the docs on RTD to use IPython shells rather than hard-coded code snippets?  I like the Ipython code blocks because they are copy-pastable by other users.  For instance: http://www.coolprop.org/coolprop/HighLevelAPI.html#propssi-function .  The IPython code is run at documentation build time.  I know how to get it working on RTD as well.  It's pretty slick overall.

I've not yet used your library, but the docs look quite nice, and I wonder if you would be interested in this addition.  If so, I'll get started.

**Comment by ljvmiranda921** [comment]
Hey @ibell , any updates on this? 

If you wish to continue with this PR, please do so in the `development` branch (not in `master`). We're planning to release v.0.2.0 (hopefully soon) and this means we'll update the docs as we go. :+1:

**Comment by whzup** [comment]
Hey @ibell, do you need some help? I'd be happy to lend a hand 😃.

**Comment by whzup** [comment]
Thanks for the guideline! I have some questions, though:
* Where do I find the requirements.txt? Should this already exist or can I create it in the `docs` folder? If so how does it have to be written?
* How is this extension called I cannot find any extension for Sphinx that is explicitly for IPyhton🙈?
* And how do I change the code snippets to be lines of an IPython shell instead of a python shell?

Sorry for the amount of questions I have no experience with readthedocs at all 😄.

**Comment by ljvmiranda921** [comment]
This is nice-to-have and can be moved for another release. Let's just wait for @ibell 's free time. Best of luck!

**Comment by ljvmiranda921** [comment]
This has already been stale for a month. Closing this for now. I'll just open this one again if there's new activity.
