### ISSUE TITLE
Handlers features from #238 removed duplicate calls fixes from #266

### ISSUE THREAD

**Issue by danielcorreia96** [ljvmiranda921/pyswarms#289]
**Describe the bug**
The PR that added boundary/velocity handlers (#238)  removed the fixes to duplicate function calls. 

**To Reproduce**
For example, check the history of GeneralOptimizer at https://github.com/ljvmiranda921/pyswarms/commits/master/pyswarms/single/general_optimizer.py

You can see that the handlers commit reverted the duplicate function call fixes (array np.inf initilization and duplicate call removal).

**Expected behavior**
Both features should exist at the same time.

**Additional context**
@ljvmiranda921, I'll try to make a PR to fix this (again) as soon as possible :)

**Comment by ljvmiranda921** [comment]
Whoops, thanks for catching @danielcorreia96 !

@whzup , can you facilitate the review on the upcoming PR? 

Would it be better to work on [this branch](https://github.com/whzup/pyswarms/tree/fix-handlers) since @whzup is introducing another fix to the handlers? So that I can just merge that one and make a patch release

**Comment by danielcorreia96** [comment]
I don't think working on top of an existing branch is a good idea: each branch should target a specific feature/problem 👍

**Comment by ljvmiranda921** [comment]
Thanks for this, @danielcorreia96 !
