### ISSUE TITLE
unexpected keyword argument 'print_step'

### ISSUE THREAD

**Issue by olixu** [ljvmiranda921/pyswarms#317]
**Describe the bug**

when i play your demo: /example/train_neural_network. it shows:

```
2019-03-06 14:50:56,821 - pyswarms.single.global_best - INFO - Optimize for 1000 iters with {'c1': 0.5, 'c2': 0.3, 'w': 0.9}
pyswarms.single.global_best:   0%|          |0/1000
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<timed exec> in <module>

~/Envs/huodian/lib/python3.7/site-packages/pyswarms/single/global_best.py in optimize(self, objective_func, iters, fast, **kwargs)
    181             # Compute cost for current position and personal best
    182             # fmt: off
--> 183             self.swarm.current_cost = objective_func(self.swarm.position, **kwargs)
    184             self.swarm.pbest_pos, self.swarm.pbest_cost = compute_pbest(self.swarm)
    185             # Set best_cost_yet_found for ftol

TypeError: f() got an unexpected keyword argument 'print_step'

```

**Environment (please complete the following information):**
 - OS: [Linux]
 - Version [manjaro 18]
 - PySwarms Version [v1.0.2]
 - Python Version [3.7.2]

**Additional context**
None

Thank you!

**Comment by stevenbw** [comment]
Hi @olixu , welcome to PySwarms!

Thank you for raising this, we are already aware of the issue (see #264 ) and are currently working on updating them. Perhaps you could work on one, if you are interested?

**Comment by lcyuanjiang** [comment]
obviously, the optimizer function  doesn't have the 'print_step' and 'verbos' interface

**Comment by ljvmiranda921** [comment]
Hi @lcyuanjiang , would you like to contribute in updating the documentation?

**Comment by ArtificialZeng** [comment]
the same situation.

**Comment by ArtificialZeng** [comment]
Did you solved this???

**Comment by lcyuanjiang** [comment]
optimize(fx.sphere,inters=20000) ,get rid of the"print_step="

**Comment by lcyuanjiang** [comment]
just get rid of the “print step”in optimize发自我的iPhone------------------ Original ------------------From: 曾小健  <notifications@github.com>Date: Wed,Apr 10,2019 1:02 PMTo: ljvmiranda921/pyswarms <pyswarms@noreply.github.com>Cc: lcyuanjiang <lcyuanjiang@sina.com>, Mention <mention@noreply.github.com>Subject: Re: [ljvmiranda921/pyswarms] unexpected keyword argument 'print_step'(#317)Did you solved this???

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/ljvmiranda921/pyswarms","title":"ljvmiranda921/pyswarms","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/ljvmiranda921/pyswarms"}},"updates":{"snippets":[{"icon":"PERSON","message":"@ArtificialZeng in #317: Did you solved this???"}],"action":{"name":"View Issue","url":"https://github.com/ljvmiranda921/pyswarms/issues/317#issuecomment-481534539"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/ljvmiranda921/pyswarms/issues/317#issuecomment-481534539",
"url": "https://github.com/ljvmiranda921/pyswarms/issues/317#issuecomment-481534539",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by ljvmiranda921** [comment]
Hopefully this is already solved. Closing this issue
