### ISSUE TITLE
BinaryPSO does not return best pos

### ISSUE THREAD

**Issue by ichbinjakes** [ljvmiranda921/pyswarms#321]
**Describe the bug**
BinaryPSO does not return best pos

**To Reproduce**
Run Feature Subset Selection [notebook](https://github.com/ljvmiranda921/pyswarms/blob/master/examples/feature_subset_selection.ipynb)

After running the optimiser, calling `f_per_particle(pos)` does not return a value equal to `cost`.

**Expected behavior**
`f_per_particle(pos) == cost` should return True

**Environment (please complete the following information):**
 - OS: [Linux]
 - Version [Ubuntu Server 18.04]
 - PySwarms Version [v.1.0.2]
 - Python Version [e.g. 3.6.8]

**Comment by ichbinjakes** [comment]
I am not sure if this is the intended behaviour. The Docs say:
```
def optimize(self, objective_func, iters, **kwargs):
    """ ....
        Returns
        -------
        tuple
            the local best cost and the local best position among the
            swarm.
        """
```
But the code comments say ```# Obtain the final best_cost and the final best_position```. Is  `final_best_pos` the overall best solution found? Is this the same or different to local best position?

The global best pos can be found with:
```
optimizer.swarm.pbest_pos[optimizer.swarm.pbest_cost.argmin(axis=0)]
# or:
optimizer.swarm.best_pos[optimizer.swarm.pbest_cost.argmin(axis=0)]
```

I can submit a PR that fixes the return value or, add a method or variable to access the global best from the BinaryPSO class.

**Comment by whzup** [comment]
Hello @ichbinjakes and welcome to pyswarms! 😄 

Thanks for your report. :+1: It seems like there is a small "typo" in the [code](https://github.com/ljvmiranda921/pyswarms/blob/master/pyswarms/discrete/binary.py#L205). Instead of the `position` argument, it should use the `best_pos` argument as you say. It should return the best position that has been found over the entire course of the optimization. Would be cool to see a PR from you. Could you also fix this bug in the other optimizers?
