### ISSUE TITLE
Restrictions

### ISSUE THREAD

**Issue by gabrielaleon** [ljvmiranda921/pyswarms#368]
I was wondering if I could add a restriction rule.
I have for dimensions and each of them have bounds, but also I need to make sure that the sum of these dimensions is equal to 1. 
In other words, every time that the particles are updated they need to respect the bounds and the sum of the dimensions of each particle must be 1.
Can I do it in this package ? Is possible to modify a function/class to consider it?

**Comment by whzup** [comment]
Hello, @gabrielaleon! At the moment it is only possible if you are willing to write your own Optimizer (for which you could copy a lot of code from the [existing optimizers](https://github.com/ljvmiranda921/pyswarms/tree/master/pyswarms/single)). I think this is similar to #259. Due to the lack of time of the maintainer team at the moment we're sadly not ready to face such a big change, though.
