### ISSUE TITLE
pathos instead of pool for multiprocessing

### ISSUE THREAD

**Issue by mnewls** [ljvmiranda921/pyswarms#450]
After attempting to use the multiprocessing functionality to speed up my training it became apparent through some troubleshooting that using multiprocessing built in from python was not supporting the code I had set up. I implemented pathos instead to support what I needed. The following **could serve as a replacement if others have run into a similar problem.

I used `from pathos.pools import ProcessPool as Pool` in the `global_best.py` file.

then used `pool = None if n_processes is None else Pool()` and it passes the pathos pool down to the operators.py file where I changed the compute_objective_function() function. 

It was necessary for me to use the following: else:
       
```python
results = pool.map(lambda pos: objective_func(pos, **kwargs), swarm.position)
return np.concatenate(results)
```

in order to get the computer to calculate multiple particles at once.

I will update this with more issues or solutions if I come across them. It is also possible I will try to further enhance this by integrating it with numba.

**Comment by ljvmiranda921** [comment]
Hey thanks for this @mnewls , not sure if we have bandwidth to work on a lot of multiprocessing for our end (although I know it's just a library change). But I'll definitely keep this one in mind! Thanks for finding a good workaround :bow: 

Note: if others find this useful, please let me know in this thread so that I can put the conversion in the backlog

**Comment by mnewls** [comment]
this is a WIP, I will post more findings as I continue to adapt it to this application. If I find an elegant solution I will submit a PR. Thanks for making the library :)
