### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by PeterDomanski** [ljvmiranda921/pyswarms#462]
Logging of pyswarms interfere with logging of absl-py. With every initialization, a new log file "report.log" is saved in the default directory. Moreover, LogLevel is always INFO for report.log. How can I use my absl-py logging file and disable pyswarm logging. In other words, how can I save output messages of pyswarm in my absl-py logging file. The suggested way (https://pyswarms.readthedocs.io/en/latest/api/pyswarms.utils.reporter.html) does not change anything. I think somewhere in your package you may initialise the root logger.

**Comment by ljvmiranda921** [comment]
Yeah, @PeterDomanski , let me find a fix for that. Definitely planning to replace the logger some time in the future using loguru. 
For now, not sure what's the best workaround. It may be on your side to filter the non-pyswarms logs. Sorry for the trouble and thanks for the patience!

**Comment by lukebemish** [comment]
Logging of pyswarms interferes with ANY sort of logging, since as far as I can tell the Reporter class overwrites already set log levels and formats whenever pyswarms classes are used, since it effectively overwrites the root logger and all of its children.

A very basic example of this issue:

    from pyswarms.utils.reporter import Reporter
    import logging
    logging.root.setLevel(10)
    logging.debug("Stuff")

Running this code, nothing at all logs. if the "debug" in the third line is replaced with "info", what logs is "date time - root - INFO - Stuff" instead of "INFO:root:Stuff"

Another example would be as follows:

    from pyswarms.utils.reporter import Reporter
    import logging
    logging.basicConfig(filename='IWantToWriteHere.log')
    logging.info("Stuff")

Which writes to report.log instead. This becomes especially problematic because this overwrite happens when any part of pyswarms that uses Reporter is imported.

**Comment by lukebemish** [comment]
Part of what I'm unsure about is whether there's actually any advantage to Reporter existing; could it simply be replaced with a rather abstracted reference to logging that doesn't use mess with logger configs, and leave the logging configs to the end user?

**Comment by ljvmiranda921** [comment]
Hi @lukebemish yes it can be replaced. Thanks fir bringing it up. Just don't have the time, sorry. Would you like to do a PR?

**Comment by lukebemish** [comment]
I have submitted a pull request; my solution was rather brute force, as I simply entirely removed the ability to set a custom logging location or format from Reporter, but this should probably be handled through the logging library instead anyways.
