### ISSUE TITLE
Save cost

### ISSUE THREAD

**Issue by HugoFara** [ljvmiranda921/pyswarms#470]
I may be wrong, but I noticed ``swarm.current_cost`` is not saved to history, and we have to recompute it after the optimization to get it. This procedure saves memory, however it has important drawbacks:
* We do need to visualize the swarm *with* cost if dimension is above 3. 
* It is a waste of resources to recompute the same data, especially when the cost function is heavy.
* Some stochastic cost function would return different cost with same input. 
* Complete cost matrix is not often a curse on memory. Cost is 1-D, in the worst case (1-D swarm), we increase memory use by **at most a third**. For at each iteration with n particles, k dimensional, we save a ``n*k position matrix + n*k velocity matrix + n*1 best cost matrix``.

In my I'm working on a project using PySwarms where the evaluation function is difficult to define in a satisfactory way, and take important resources to compute. For this reason I want to save cost, and started working on it on a fork.

Would you consider saving cost by default?

**Comment by ljvmiranda921** [comment]
Hi @HugoFara , [we do save the best cost for the swarm](https://github.com/ljvmiranda921/pyswarms/blob/d928dfda3c9ad78be731d432bb06aecd78c2a497/pyswarms/base/base_single.py#L113), but I'm not sure if that's what you're referring to. Or do you mean all the computed cost for each particle at a given iteration?

**If it's the latter, yeah, I do have an apprehension on memory.** I'm fine saving it, but maybe we can add a `save_history=False` parameter in `optimize()` so that the user is aware of the implications when saving to memory (I had some issues from users where each iteration step takes up a lot of RAM). Would you like to make a PR?

**Comment by HugoFara** [comment]
Yes I was referring to the current_cost matrix. The best cost is memory efficient but we loose a lot of information (which is normal).

I already have a functional branch with cost saving, so I can make a PR. I added a key ``all_cost_history`` (any idea for a better name?) to  `` ``ToHistory``. 

My only concern is that ToHistory is a ``namedtuple``, so will be very awkward to have one version with a complete cost matrix if we set ``save_history=True``, and another version  without. So I was just thinking to let the ``all_cost_history`` empty if we set ``save_history`` to ``False``, are you okay with that?
