### ISSUE TITLE
[DOC] Allow easier access to different doc pages

### ISSUE THREAD

**Issue by stsievert** [ljvmiranda921/pyswarms#61]
Going from two pages on the documentation requires going to an intermediate page. For example, going from [discrete.binary] to [single.global_best module] requires two clicks.

On the discrete.binary page, I see no link to single.global_best. That's illustrated by the figures below:

| discrete.binary | single.global_best |
| :--:|:---:|
| <img width="299" alt="screen shot 2017-11-02 at 2 43 31 pm" src="https://user-images.githubusercontent.com/1320475/32346750-50e57be6-bfdc-11e7-8295-8800a577bca5.png"> |<img width="299" alt="screen shot 2017-11-02 at 2 43 41 pm" src="https://user-images.githubusercontent.com/1320475/32346751-50f4e3a6-bfdc-11e7-8b96-7f99a2225148.png"> |

It would be useful to have links in-between sections.

This isn't blocking for https://github.com/openjournals/joss-reviews/issues/433 but it'd make docs for this package more accessible.

[discrete.binary]:https://pyswarms.readthedocs.io/en/latest/api/pyswarms.discrete.html#module-pyswarms.discrete.binary

The documentation would be easier to use if this was resolved.

**Comment by stsievert** [comment]
I think this could be resolved by calling "API Documentation" a section (not a subsection)

**Comment by ljvmiranda921** [comment]
Hi @stsievert , sorry I just saw this now. Thank you for the feedback and I’ll work on this right away.

**Comment by ljvmiranda921** [comment]
Hi @stsievert , 


I accomplished moving the **API Documentation** subsection in its own section, which I think is a really good suggestion, but the problem

> Going from two pages on the documentation requires going to an intermediate page. For example, going from discrete.binary to [single.global_best module] requires two clicks.

still persists. It turns out that one really has to click the specific package (`pyswarms.single` or `pyswarms.discrete`) to access the modules inside of it. 

I'm thinking of removing the upper-level hierarchy (`pyswarms.single`, `pyswarms.discrete`), but I prefer PR #64 's set-up more because it divides the optimizers wrt the specific problem they're trying to solve (i.e. single-objective, discrete-optim). This also provides a good structure in case we expand to different problem types (e.g. `pyswarms.multi` or `pyswarms.constrained` for multi-objective and constrained). 

I'm still looking for a JS workaround to automatically expose all the modules right away without having to click, but it might take more time.

### Move API Documentation as a new Section
![new toc](https://user-images.githubusercontent.com/12949683/32529712-62662410-c47d-11e7-8880-9ae0e5c3c669.PNG)

### Comparison
| discrete.binary | single.global_best |
| :--:|:---:|
| <img width="299" alt="pyswarms toc discrete" src="https://user-images.githubusercontent.com/12949683/32529659-0f2c4e3c-c47d-11e7-9da5-6bc952530f10.PNG"> |<img width="299" alt="pyswarms toc single" src="https://user-images.githubusercontent.com/12949683/32529662-14f32ec6-c47d-11e7-9ce1-88c3f26dc29b.PNG"> |

**Comment by stsievert** [comment]
A JS solution feels like a hack, and it looks like reduced the number of clicks required to navigate (ie, going from optimizers to utilizes looks easier).

**Comment by ljvmiranda921** [comment]
Hi @stsievert ,

> A JS solution feels like a hack

Well I feel the same way. I think it's part of Sphinx that the dropdown only appears depending on the page you are in.

Another way would be to remove the package hierarchy altogether (`single`, `discrete`), so as to expose the modules inside (`global_best`, `local_best`, `discrete`)&mdash; but I believe it's better to maintain the current structure, so the problem domains are much clearer (and scalable if new variants come in the future). What do you think?

> it looks like reduced the number of clicks required to navigate (ie, going from optimizers to utilizes looks easier).

Yes it does, your suggestion to move API Documentation up one section is actually good. Thanks! 👍

**Comment by stsievert** [comment]
> to remove the package hierarchy altogether (single, discrete), 

I think the hierarchy should stay, it sounds like it adds some useful information.

> reduced the number of clicks required to navigate ... Yes it does

Then this issue is addressed. I’m comfortable closing it.

**Comment by ljvmiranda921** [comment]
Thanks a lot, @stsievert !

Merged #64
